server:
  port: 8080
  shutdown: GRACEFUL


management:
  health:
    probes:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - refresh