apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: app-external-configs
    data:
      external-configs.yaml: |-
        demo:
          greeting:
            message: 'Hello World from Kubernetes!!'
        server:
          servlet:
            context-path: /ms1/api

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: microservice-one-deployment
    spec:
      selector:
        matchLabels:
          app: microservice-one
      template:
        metadata:
          labels:
            app: microservice-one
        spec:
          containers:
            - name: ms-1
              image: sriramponangi/config-management-and-updates-demo-eg-1-ms-1:v1.0.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /app/config
                  name: config-volume
              env:
                - name: SPRING_CONFIG_IMPORT
                  value: /app/config/external-configs.yaml
              readinessProbe:
                httpGet:
                  port: 80
                  path: /ms1/api/actuator/health/readiness
              livenessProbe:
                httpGet:
                  port: 80
                  path: /ms1/api/actuator/health/liveness
              ports:
                - containerPort: 80
          volumes:
            - name: config-volume
              configMap:
                name: app-external-configs

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: microservice-one
      name: microservice-one
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 80
          nodePort: 30080
      selector:
        app: microservice-one
      type: NodePort