server:
  port: 8080
  shutdown: GRACEFUL


info:
  app:
    name: "Demo-1:Microservice-One"
    instanceId: ${random.uuid}


management:
  # Configuring a separate management port for the actuator endpoints for security purposes.
  # For example, add management port specific network-policies in kubernetes for internal monitoring tools.
  server:
    port: 9090

  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true

      # Having a separate management port could lead to unreliable health checks because the
      # main application running on a different port might not work properly even if the health check is successful on management port.
      # Therefore it is better to configure the health group with an additional path on the main application port as follows:
      group:
        readiness:
          additional-path: "server:/readiness"
        liveness:
          additional-path: "server:/liveness"


  info:
    java:
      enabled: true
    os:
      enabled: true

    # This env.enabled=true display the static properties mentioned under the info property
    # (Eg: info.app.name and info.app.instanceId) to be added to the response of /actuator/info API.
    env:
      enabled: true


  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - refresh